[auth0]
client_id = "s5usTQVmXREySo103GYpugjtzuqeBtAK"
client_secret = "F1xDZn8HLI62xI6i51OwhTfkmarmZExHGlQEORfAtjH5jo1nGWisK8trgUIa5gG-"
domain = "dev-odfagjfhhjpg812i.us.auth0.com" 
OPENAI_API_KEY = "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"

